# Generated by Django 3.2.9 on 2021-11-12 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConditionOccurrence',
        ),
        migrations.DeleteModel(
            name='Death',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='ProcedureOccurrence',
        ),
    ]
